### ISSUE TITLE
Conversion errors to card

### ISSUE THREAD

**Issue by davyvr** [w1tw0lf/Unifi-Device-info#5]
FYI, I had to make 2 changes to get the card working:
* Attributes "2Ghz" & "5Ghz" don't exist in my case, They are called "Score_wifi0" and "Score_wifi1".
* Activity had a unit behind it (" Mbps") so couldn't be displayed in the graph. So I had to make this change in sensors.yaml (added the **[:-5]**):
```
unifi_ap_liv_activity:
  value_template: >
    {{ states.sensor.unifi_ap_liv.attributes.Activity[:-5] }}
  unit_of_measurement: 'Mbps'
  friendly_name_template: Unifi AP Living Activity
```
Don't know if it's general for all versions, but I just wanted to mention it.

All working perfect now. Thanks for the effort put into this!
